= Miod v4 language spec
(C) 2022-2024
:toc:


== Types
Values types (PrimitiveType), automatically converted to references in generic
classes/procs:

    - Int -- 32-bit integer
    - Long -- 64-bit integer
    - Float -- 32-bit float
    - Double -- 64-bit float
    - Bool -- boolean type, true/false

Aggregated values are created with a *class* type, which is a reference with
data fields and methods.

[source]
----
@_lang_item
baseclass PrimitiveType
endclass
----


== Class type
A class is a structure with data fields and associated methods, that supports
inheritance and polymorphism with virtual methods.

A class that can have virtual methods and be inherited from is declared with
the *baseclass* keyword. The virtual methods are introduced in the fields block.
If the class provides default implementation, those methods must be declared with
the *implemented* keyword.

Special argument *self* does not require type declaration, and is required even
if it's unused.

Methods without *self* are static and are called with _ClassName::method_name_
form.

A final class is declared with the *class* keyword, it cannot introduce new
virtual methods, and cannot be inherited from.

An instance is constructed with field names paired with values between curly
braces. See examples below.

[source]
----
baseclass AbstractClass
  pub proc abstract_method(self)
  proc virtual_method_with_default_impl(self): Bool, implemented

  prop x: Int
  var y: Double
  pub var z: String
endclass

proc AbstractClass::virtual_method_with_default_impl(self): Bool
  return true
end

class Inherited(AbstractClass)
endclass

proc Inherited::abstract_method(self), override
end

proc Inherited::new(): Inherited
    return Inherited { x: 3, y: 4.0, z: "abc" }
end
----

=== Properties
Properties are public class fields which can have private setters and getters,
and exported through RTTI for reflection.

Class's methods do not use getters/setters when they assign or read the properties.

=== Fields
Class data fields can be private and public. Private fields are accessible only
within the same module.

=== Methods
Class can have _static_, normal, and virtual methods. Static methods only use a
namespace of a class. Virtual methods are declared in a _base_ class
(*_baseclass_* keyword), and implemented with an *override* keyword in the
proc declaration.


=== Base class default methods

==== as_string(): String
In debug mode (debug build tag) default implementation displays all fields.
In release mode only the class name and pointer value is displayed.

==== hash_value(): Int
Returns pointer value (or the lowest 32 bits)

==== equals(): Bool
Returns pointer value comparison.

==== id(): Long
Returns the pointer value.

[source]
----
@_lang_item
baseclass Base
proc as_string(): String
proc hash_value(): Int
proc equals(other: Base): Bool
endclass

proc Base::id(): Long
----

== Metadata: annotations and build tags

Annotations affect code generation and add metadata to a class.

Buld tags affect which annotations are enabled and which import, const, proc,
class, union, enum declaration is compiled.

[source]
----
class _lang_item
endclass

@_lang_item
class None
endclass

const none = None {}

# Buld tag example: _reflect_fields annotation is applied only if 'debug' tag
# is specified during the compilation.
# The class is not compiled at all if 'windows' build tag is not set.
@@debug
@_reflect_fields
@@windows
class WindowsImpl(ImplBase)
endclass

----

@class_name -- annotation, applies to the following class, import, proc, const,
let, var

@@build_tag -- affect the next element to be semantically effective only if the
build tag is set, e.g. affects only the next annotation or class/import/proc etc.

== Magic annotations

@_lang_item -- denotes a language-related feature, possible automatic treatment
of the type by the compiler.

@_equals -- generates 'equals' method with field by field comparison (calling
'equals' method for each field).

@_hash -- generates hash by calling 'hash' for each field, stores the result
for consecutive calls.

@_data -- all fields become read-only properties, properties are always public,
generates 'equals' and 'hash'.

@_atomic_rc -- atomic reference counter, required for classes used in multithreaded code.

== Enum type
Enum is a class with defined global instances. A new instance cannot be
constructed, only the constants can be used.

[source]
----
enum Day
  today,
  tomorrow,
  yesterday
endenum

const today = Day::today

proc is_it_today(day: Day): Bool
  switch day
    case today:
        return True
    endcase
    else
      return False
  endswitch
  return False
end
----

== Union type
A union type is a class instance which can hold only a specified class instance
inside thus makes the programmer cover all possible classes.

[source]
----

class Some!<V>
prop value: V
endclass

class Error!<E>
prop error: E
endclass

union Result
  Some!<V>,
  Error!<E>,
  None,
endunion

proc as_string(o: Base): Result
...

proc do(o: Base)
  let res = as_string(o)
  # in case of union type non-covered cases trigger compilation error
  # if the variable is just a Base class, then no such check is performed.
  switch_class res
    # case casts res to String here
    case String print(res.length)
    endcase
    else
      print("error")
  endswitch
end
----

== Generics
Generics are implemented as syntactic sugar. All generic
type parameters are not visible in runtime, and only one version of code
is generated which operates on Base class instance type instead of concrete
types. So it's a compile-time only feature to circumvent switch_class casts.

== Memory management
Reference types are managed by counters: autoincremented on copying, and
decremented when go out of scope, and destroyed upon reaching zero.

Arguments passed to a procedure are not autoincremented and must be released
by the caller upon return.

A reference returned from a function call must be deincremented, it's done
by the compiler. A returned reference is autoincremented by the compiler before
exiting the proc body.

== Constants
A constant declared with a *const* keyword can only store a literal (string,
integer, float) or enum.

== Arguments
Arguments cannot be assigned, treat argument names as declared with *let*.

== Variables
Only local (declared in a proc body) variables are supported:

    - *let* declares a variable which can be assigned once;
    - *var* declares a variable which can be reassigned.

== Name mangling
Generated C code encodes identifiers in the following way:

    - 'miod_' + 'module-name' + '_class-name' + '_identifier'

== Integration with C
C procs can be called from Miod via *cproc* declarations:

[source]
----
# cproc uses unmagled name if it's not a class method. A real C function name
# can be specified via the annotation.
@_cname { "my_sort_array" }
cproc sort_array<C>(data: Array!<C>): Array!<C>

----

== Multithreading and data
TBD

== Code samples

[source]
----


# automatically imported everything from 'miod' module for
# basic language stuff like None, String types etc
importall miod

# Double
const pi = 3.14
# Float
const pi_f = 3.14f
# Int
const count = 7
# Long
const count_long = 7L

const name = "abc"

# ancestor for boxed types like Int, Long, Float, Double, Flags
# primitive values are passed by copy and boxed if used in generics
pub baseclass Primitive
endclass


# abstract methods are declared among class fields
pub baseclass Any
    # with default value
    some_private: Int = 3
    pub some_inherited: Int
    pub const some_const = "aaa"

    pub proc hash(self): Int
    pub proc as_string(self): String
endclass

# final class
class AnyBase(Any)
endclass

proc AnyBase::hash(self): Int, override
    some_private + some_inherited
end

proc AnyBase::new(): Any
    AnyBase{ some_private: 3, some_inherited: 4}
end


pub baseclass Runnable
pub proc run(self)
end

# anonymous class def and instantiation shortcut
proc myproc()
    var c = 3

    # for abstract base classes with single method
    # captured vars are copied into instance vars
    let a = proc Runnable::run(self)
        for i in range(c)
            let h = hex(i)
            print("$h\n")
        endfor
    end

    inc(c)
    # captured 'c' in 'a' is still 3, because it was copied
    # class instances are the only reference types
end

# max 64 flags, because of underlying 64 bit integer
flags Access
    read,
    write,
endflags

const rw = Access.read | Acces.write

union Optional$<T>
    T,
    None
endunion

baseclass AbstractEnum$<E>
proc from_string(s:String): E
proc as_string(self): String
proc index(self): i32
endclass

enum Mixed
  one,
  two,
  three,
  max
endenum


baseclass AbstractUnion
prop value: Any, set(set_value)
proc set(self, new_value: Any)
endclass

# hidden generated code:
class FileResult(AbstractUnion)
endclass

# this is actually bad, since panic on serialization is wrong
proc FileResult::set(self, new_value: Any)
    switch class_of(new_value)
    case f: File 
        value = f
    endcase
    case e: IoError
        value = e
    endcase
    else
        let name = class_name(new_value)
        panic("cannot set union value, class $name is not in union FileResult")
    endswitch
end
  
union FileResult
  File,
  IoError
endunion

proc open_file(fn: String): FileResult

@_lang_item
class None
endclass

# compile-time type, will fail if ItemClass is a union
union IteratorResult$<ItemClass>
    ItemClass,
    None
endunion

baseclass Iterator$<ItemClass>
    proc next(self): IteratorResult$<ItemClass>

endclass


class Immutable
prop x: Int, get()
prop y: Int, get()
endclass

enum None
  none
endenum

pub const none = None.none



union FileResult
File,
Error
endunion


baseclass BaseUnion
prop possible_types: List, get()

endclass

class FileResultClass
endclass

let ClassOfFileResult = FileResultClass { possible_types:  [File, Error] }


----

== Possible simplification
Generics, unions are syntactic sugar which do not exist at runtime.
To allow for more secure serialization/deserialization one should create
a concrete implementation with checks.

E.g.

[source]
----
union FileResultValues
File,
Error
endunion
proc file_open(fn: String): FileResultValues

# actually generates
proc file_open(fn: String): Any


----

